### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by Gaelan** [Shwam3/EASMData#4]
I noticed that this repository doesn't currently have a license - is that an intentional choice, or would you consider adding one?

(I ask because I'm investigating building my own signal map - I've long wanted one that supports replaying archived signaling data - and being able to reuse your work would make doing so vastly easier!)

**Comment by mhuxtable** [comment]
The work in this repo is really fantastic and I'd also be interested in reusing it for a small number of (free, open source) projects if it was appropriately licensed.

**Comment by Shwam3** [comment]
A license has now beed added https://github.com/Shwam3/EASMData/commit/76ad5669ce8e351716a1b5b79e8c12fad60dd89b
